baseurl = "https://sonohen.github.io/"
languageCode = "ja-jp"
title = "sonohen's tech log"
theme = "roadster"
pagination.pagerSize = 9
disqusShortname = "xxxx"
MetaDataFormat = "toml"
pygmentsUseClasses = true
pygmentsCodefences = true

copyright = "© 2020-2025 sonohen All Rights Reserved."

[Params]
  subtitle = "Just another tech blog." # optional
  github = "sonohen" # optional
  customCSS = ["css/syntax.css"]
  googleFontsLink = "https://fonts.googleapis.com/css2?family=BIZ+UDPGothic&display=swap"
  post_meta = ["author", "date", "categories", "translations"]
  authorbox = true
  [params.author]
    name = "sonohen"
    bio = "Debian GNU/Linux | Emacs | ThinkPad | MacBook M3 | Swift | Lisp"
  [Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["social", "search", "recent", "categories", "taglist"]
  [Params.widgets.social]
    x = "nya18nn"
    github = "sonohen"
  [Params.style.vars]
    fontFamilyPrimary = "'Zen Kurenaido', sans-serif"

[permalinks]
  post = "/:year/:month/:day/:contentbasename/" # optional
    
