[[social]]
    identifier = "github"
    name       = "GitHub"
    url        = "https://github.com/sonohen/"
    weight     = 1
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "RSS"
    name       = "RSS"
    url        = "/index.xml"
    weight     = 4
    [social.params]
        icon = "rss"


